AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test function
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Handler: index.handler
    Runtime: nodejs10.x
